MDA/Coupons/urls.py
from django.urls import path
from Coupons import views



urlpatterns = [
    
    path('coupons/', views.Coupon_SU_table, name="SUCoupon_table"),
    path('superuser_couponcode/', views.create_SU_coupon_, name='SuCoupon'),

]

MDA/MDA/urls.py
from django.contrib import admin
from django.urls import path, include
from socius import views as v
from directory import views as vd
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', v.index, name="index"),
    path('index.html', v.index, name="index"),
    path('directorypage.html', v.directorypage, name="directorypage"),
    path('team.html', v.Team, name="team"),
    path('create', v.create, name="create"),
    path('members',v.members,name="members"),
    path('joined',v.joined,name="joined"),
    path('joindirectory',v.joindirectory,name="joindirectory"),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include('Coupons.urls')),
    path('adduser/',v.simple_upload,name='simple_upload'),
    path('active/<uidb64>/<token>/',v.active, name='active'),
    
]


urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

MDA/Coupons/models.py
from django.db import models
import random, datetime
from socius.models import UserList
from django.contrib.auth.models import User


class Coupon_SU(models.Model):

    CATEGORY = (
        ('Admin', 'Admin'),
        ('Member', 'Member')
    )

    Name = models.CharField(max_length=10, null=True)
    category = models.CharField(max_length=100, null=True, choices=CATEGORY)
    code = models.CharField(max_length=10, unique=True, null=False)
    description = models.TextField(default=None, blank=True, null=True)
    valid_from = models.DateField(default=datetime.date.today)
    valid_till = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.code

MDA/Coupons/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms
from django.conf import settings
from .models import Coupon_SU

class DateInput(forms.DateInput):
    input_type = "date"
    input_formats = "dd/mm/yyyy"


class Coupon_code_SU_(ModelForm):
    
    valid_from = forms.DateField(widget=DateInput)
    valid_till = forms.DateField(widget=DateInput)
    class Meta:
        model = Coupon_SU
        fields = "__all__"

MDA/Coupons/views.py
from django.shortcuts import render, redirect
from .models import Coupon_SU 
from .forms import Coupon_code_SU_
from django.contrib import messages

def create_SU_coupon_(request):

    context = {}
    form_su = Coupon_code_SU_(request.POST)
    if request.method == 'POST':
        if form_su.is_valid():
            form_su.save()
            code = form_su.cleaned_data.get('code')
            messages.success(request, 'Coupon Code is generated successfully!')
            return redirect('SuCoupon') 
    
    else:
        form_su = Coupon_code_SU_()

    context['form_su'] = form_su

    return render(request, 'Coupons/CouponSUGeneration.html', context)


def Coupon_SU_table(request):
    coupons = Coupon_SU.objects.filter(Name = request.user.get_username())
    return render(request, 'Coupons/CouponsSU_table.html', {'coupons':coupons})

MDA/Coupons/templates/Coupons/CouponSUGeneration.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <style>
        form {
          max-width: 500px;
          margin: 10px auto;
          padding: 10px 20px;
          background: #f4f7f8;
          border-radius: 8px;
        }
    </style>
	

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'Coupons/main.css' %}">
	
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}    
    {% endif %}
    
	<button class="btn btn-outline-info" style="float:right" onclick="location.href='{% url 'Coupons' %}'">View Coupons</button>
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb=4">Coupon Generator</legend>
				<p> Category {{ form_su.category }} </p>
				<p> Code: {{ form_su.code }} 
					<button class="btn btn-outline-info" onclick="generate()" type="button">Generate</button>
				</p>
						<p> Description: {{ form_su.description }} </p>
						<p> Valid from: {{ form_su.valid_from }} YYYY-MM-DD </p>
						<p> Valid till: {{ form_su.valid_till }} YYYY-MM-DD </p>
						<p> Active: {{ form_su.active }} </p>
				
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Save</button>
			</div>
		</form>		
	</div>

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script>
    	function generate(){
    		var code_chars = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
     		var code_10 = '';
     		var code_8 = '';

     		if (document.getElementById("id_category").value == 'Admin'){
     			for(var i=0;i<10;i++){
     			var slice_start = Math.floor(Math.random() * 35) + 1;
     			code_10 += code_chars.slice(slice_start, slice_start + 1);
     		}
     		document.querySelector("#id_code").value = code_10;
     		}

     		else if (document.getElementById("id_category").value == 'Member'){
     			for(var i=0;i<8;i++){
     			var slice_start = Math.floor(Math.random() * 35) + 1;
     			code_8 += code_chars.slice(slice_start, slice_start + 1);
     		}
     		document.querySelector("#id_code").value = code_8;
     		}
    	}
    </script>

</body>
</html>